INSERT INTO Movie (DESCRIPTION, DURATION, FILM_DIRECTOR, GENRE, TITLE, IMAGE_URL) VALUES ('A family-friendly animated film featuring Barbie and her adventures.', INTERVAL '7200' SECOND, 'Unknown Director', 'Animation, Family', 'Barbie', 'https://i.imgur.com/Qyvx7oX.jpg');
INSERT INTO Movie (DESCRIPTION, DURATION, FILM_DIRECTOR, GENRE, TITLE, IMAGE_URL) VALUES ('A biographical drama about the life of J. Robert Oppenheimer, the physicist who led the Manhattan Project during World War II.', INTERVAL '7200' SECOND, 'Christopher Nolan', 'Biography, Drama', 'Oppenheimer', 'https://i.imgur.com/cbPxaMu.jpg');
INSERT INTO Movie (DESCRIPTION, DURATION, FILM_DIRECTOR, GENRE, TITLE, IMAGE_URL) VALUES ('A science fiction action film directed by Christopher Nolan.', INTERVAL '8880' SECOND, 'Christopher Nolan', 'Action, Sci-Fi', 'Inception', 'https://i.imgur.com/aCbKufn.jpg');

INSERT INTO Screening_Room (NUMBER, ROW_QUANTITY, SEATS_PER_ROW) VALUES (1, 5, 8);
INSERT INTO Screening_Room (NUMBER, ROW_QUANTITY, SEATS_PER_ROW) VALUES (2, 4, 6);
INSERT INTO Screening_Room (NUMBER, ROW_QUANTITY, SEATS_PER_ROW) VALUES (3, 5, 5);

INSERT INTO Screening (START_TIME, MOVIE_ID, SCREENING_ROOM_ID) VALUES ('2023-09-14 23:40:00', 2, 1);

INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 1, 1, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 1, 2, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 1, 3, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 1, 4, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 5, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 6, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 7, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 8, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 1, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 2, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 3, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 4, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 5, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 6, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 7, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 2, 8, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 1, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 3, 2, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 3, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 3, 4, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 5, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 6, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 3, 7, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 8, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 4, 1, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 4, 2, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 4, 3, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 4, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 5, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 6, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 7, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 8, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 1, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 2, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 3, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 4, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 5, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 6, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 7, 1);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 8, 1);

INSERT INTO Screening (START_TIME, MOVIE_ID, SCREENING_ROOM_ID) VALUES ('2023-09-14 12:30:00', 3, 1);

INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 1, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 2, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 3, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 4, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 5, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 6, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 7, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 8, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 1, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 2, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 3, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 4, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 5, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 6, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 7, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 8, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 1, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 2, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 3, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 4, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 5, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 6, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 7, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 8, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 1, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 2, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 3, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 4, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 5, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 6, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 7, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 8, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 1, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 2, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 3, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 4, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 5, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 6, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 7, 2);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 8, 2);

INSERT INTO Screening (START_TIME, MOVIE_ID, SCREENING_ROOM_ID) VALUES ('2023-09-14 12:30:00', 2, 2);

INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 1, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 2, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 3, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 4, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 5, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 6, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 1, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 2, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 3, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 4, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 5, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 6, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 1, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 2, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 3, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 4, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 5, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 6, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 1, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 2, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 3, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 4, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 5, 3);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 6, 3);

INSERT INTO Screening (START_TIME, MOVIE_ID, SCREENING_ROOM_ID) VALUES ('2023-09-15 10:45:00', 1, 2);

INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 1, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 2, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 3, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 4, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 5, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 6, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 1, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 2, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 3, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 4, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 5, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 6, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 1, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 2, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 3, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 4, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 5, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 6, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 1, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 2, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 3, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 4, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 5, 4);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 6, 4);

INSERT INTO Screening (START_TIME, MOVIE_ID, SCREENING_ROOM_ID) VALUES ('2023-09-15 16:45:00', 1, 3);

INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 1, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 2, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 3, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 4, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 1, 5, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 1, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 2, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 3, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 4, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 5, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 1, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 2, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 3, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 4, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 5, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 1, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 2, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 3, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 4, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 5, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 1, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 2, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 3, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 4, 5);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 5, 5);

INSERT INTO Screening (START_TIME, MOVIE_ID, SCREENING_ROOM_ID) VALUES ('2023-09-15 20:45:00', 2, 3);

INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 1, 1, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 1, 2, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 1, 3, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 1, 4, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 1, 5, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 1, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 2, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 3, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 4, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 2, 5, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 1, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 2, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 3, 3, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 3, 4, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 3, 5, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 1, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 4, 2, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 3, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 4, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 4, 5, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (FALSE, 5, 1, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 5, 2, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 5, 3, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 5, 4, 6);
INSERT INTO Seat (is_reserved, row_number, seat_number, screening_id) VALUES (TRUE, 5, 5, 6);
